### ISSUE TITLE
ImportError: cannot import name 'Update' from 'telegram'

### ISSUE THREAD

**Issue by vitalii-tt** [Arxdust/pihole2telegram#2]
I have deployed a telegram bot (with Django) on Heroku with `python` version `3.6.9`
It worked well without any issues.
After months I did some changes and while trying to deploy it again I get issues.
Heroku doesn't support `python 3.6.9` anymore. It supports `3.6.10`
So I set up venv with python 3.6.10 and I'm still getting the same issue after running the server.
Short issue:
`    from .callbackcontext import CallbackContext
  File "/home/usr/bot-name/venv/lib/python3.6/site-packages/telegram/ext/callbackcontext.py", line 21, in <module>
    from telegram import Update
ImportError: cannot import name 'Update' from 'telegram' (/home/usr/bot-name/venv/lib/python3.6/site-packages/telegram/__init__.py)`

Also I have tried `python 3.7.6` (it's also supported by Heroku) but I get the same issue after running the server:

_python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/usr/bot-name/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/usr/bot-name/venv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/usr/bot-name/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "/home/usr/bot-name/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/home/usr/bot-name/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/usr/bot-name/venv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/usr/bot-name/venv/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/usr/bot-name/venv/lib/python3.7/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/home/usr/bot-name/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/usr/bot-name/venv/lib/python3.7/site-packages/django_telegrambot/apps.py", line 9, in <module>
    from telegram.ext import Dispatcher
  File "/home/usr/bot-name/venv/lib/python3.7/site-packages/telegram/ext/__init__.py", line 25, in <module>
    from .callbackcontext import CallbackContext
  File "/home/usr/bot-name/venv/lib/python3.7/site-packages/telegram/ext/callbackcontext.py", line 21, in <module>
    from telegram import Update
ImportError: cannot import name 'Update' from 'telegram' (/home/usr/bot-name/venv/lib/python3.7/site-packages/telegram/__init__.py)_

Here you can find my requirements file:
[requirements.txt](https://github.com/Arxdust/pihole2telegram/files/4308693/requirements.txt)

**Comment by Popolon** [comment]
try:

<pre>
pip uninstall telegram
pip install python-telegram-bot
</pre>
